[package]
name = "chemodots-toolkit"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
itertools = "0.12"
serde_json = "1.0"
chemodots-db = { path = "../db" }
rdkit-rust = { path = "../../../rdkit-rust" }
